#!/bin/bash
echo "🔍 SEO Submission Guide for CanadaAccountants"
echo "=============================================="
echo ""
echo "1. Google Search Console:"
echo "   - Go to: https://search.google.com/search-console"
echo "   - Add property: canadaaccountants.web.app"
echo "   - Submit sitemap: https://canadaaccountants.web.app/sitemap.xml"
echo ""
echo "2. Bing Webmaster Tools:"
echo "   - Go to: https://www.bing.com/webmasters"
echo "   - Add site: canadaaccountants.web.app"
echo "   - Submit sitemap: https://canadaaccountants.web.app/sitemap.xml"
echo ""
echo "3. Manual URL Submissions:"
echo "   - Google: Submit https://canadaaccountants.web.app for indexing"
echo "   - Check indexing status in 24-48 hours"
echo ""
echo "4. Local Business Listings:"
echo "   - Google My Business (if applicable)"
echo "   - Canadian business directories"
echo ""
echo "5. Test Your SEO:"
echo "   - PageSpeed Insights: https://pagespeed.web.dev"
echo "   - Test URL: https://canadaaccountants.web.app"
echo ""
